coverage:
  ignore:
    - "APIGateway.MluviiWebhook/program.cs"
    - "APIGateway.MluviiWebhook/EndpointsConfigurator.cs"
    - "APIGateway.MluviiWebhook/MluviiWebhookHealthCheck.cs"
    - "APIGateway.MluviiWebhook/OpenTelemetry/*"
    - "APIGateway.MluviiWebhook/ServiceExtensions.cs"