name: Build and Publish NuGet

on:
  push:
    branches:
      - master
    paths:
      - 'APIGateway.MluviiWebhook.Contracts/**'

jobs:
  build-and-push:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0'

    - name: Build
      run: dotnet build APIGateway.MluviiWebhook.Contracts/APIGateway.MluviiWebhook.Contracts.csproj --configuration Release --no-restore

    - name: Pack
      run: dotnet pack APIGateway.MluviiWebhook.Contracts/APIGateway.MluviiWebhook.Contracts.csproj --no-build --configuration Release /p:PackageVersion=${{ github.run_number }} -o nupkg

    # Push NuGet Package
    - name: Push
      run: dotnet nuget push nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

