name: Build and Publish NuGet

on:
  push:
    branches:
      - master
    paths:
      - 'APIGateway.MluviiWebhook.Contracts/**'

jobs:
  build-and-push:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies
      run: dotnet restore APIGateway.MluviiWebhook.Contracts/APIGateway.MluviiWebhook.Contracts.csproj

    - name: Build
      run: dotnet build APIGateway.MluviiWebhook.Contracts/APIGateway.MluviiWebhook.Contracts.csproj --configuration Release --no-restore

    - name: Pack
      run: dotnet pack APIGateway.MluviiWebhook.Contracts/APIGateway.MluviiWebhook.Contracts.csproj --no-build --configuration Release /p:PackageVersion=1.${{ github.run_number }} -o nupkg

    # List files in the package directory
    - name: List files in the nupkg directory
      run: ls nupkg

    # Push NuGet Package
    - name: Push to nugetorg
      run: Get-ChildItem nupkg -Filter *.nupkg | Foreach-Object { dotnet nuget push $_.FullName --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY  }} --skip-duplicate }
      env:
        GITHUB_TOKEN : ${{ secrets.NUGET_API_KEY  }}

    - name: Push github nuget
      run: Get-ChildItem nupkg -Filter *.nupkg | Foreach-Object { dotnet nuget push $_.FullName --source https://nuget.pkg.github.com/ObseumEU/index.json --api-key ${{ secrets.GITHUB_TOKEN  }} --skip-duplicate }
      env:
        GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN  }}